### ISSUE TITLE
Exception Value: 'orcid_active' on specific browser config

### ISSUE THREAD

**Issue by xhub** [pretalx/pretalx-orcid#4]
When trying to use ORCID from a "Incognito" windows on a Chromebook, I get this error 

```
Environment:


Request Method: GET
Request URL: http://fbp2020.de/cfp/p/orcid/oauth?code=5qUo8O

Django Version: 2.2.7
Python Version: 3.6.9
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'compressor',
 'djangoformsetjs',
 'django_filters',
 'jquery',
 'rest_framework.authtoken',
 'rules',
 'pretalx.api',
 'pretalx.common',
 'pretalx.event',
 'pretalx.mail',
 'pretalx.person',
 'pretalx.schedule',
 'pretalx.submission',
 'pretalx.agenda',
 'pretalx.cfp',
 'pretalx.orga',
 'bootstrap4',
 'django.forms',
 'rest_framework',
 'pretalx_orcid']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.middleware.common.CommonMiddleware',
 'pretalx.common.middleware.SessionMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'pretalx.common.auth.AuthenticationTokenMiddleware',
 'pretalx.common.middleware.MultiDomainMiddleware',
 'pretalx.common.middleware.EventPermissionMiddleware',
 'pretalx.common.middleware.CsrfViewMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'csp.middleware.CSPMiddleware']



Traceback:

File "/home/fbp2020/venv-pretalx/lib64/python3.6/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/home/fbp2020/venv-pretalx/lib64/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/home/fbp2020/venv-pretalx/lib64/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/fbp2020/pretalx-orcid/pretalx_orcid/views.py" in orcid_oauth
  138.     tmpid = request.session["orcid_active"]

File "/home/fbp2020/venv-pretalx/lib64/python3.6/site-packages/django/contrib/sessions/backends/base.py" in __getitem__
  54.         return self._session[key]

Exception Type: KeyError at /cfp/p/orcid/oauth
Exception Value: 'orcid_active'
```

This is not reproducible on mobile, nor on mobile or desktop firefox. The regular Chrome tab also show those issues. However, it doesn't seem to be 100% reproducable.

Chrome version
```

Google Chrome | 78.0.3904.106 (Official Build) (64-bit)
-- | --
Revision | 8543c99173fbc36cf5ce3019f07b7ab3539ca10f-refs/branch-heads/3904@{#879}
Platform | 12499.66.0 (Official Build) stable-channel swanky
Firmware Version | Google_Swanky.5216.238.150
JavaScript | V8 7.8.279.23
Flash | 32.0.0.293 /opt/google/chrome/pepper/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.106 Safari/537.36
```

**Comment by xhub** [comment]
I managed to reproduce the issue. The crash is easily reproducible anywhere using the following setup:
- go on https://www.fbp2020.de/cfp
- try to use the orcid login, it will fail

The server config has `www.fbp2020.de` as name, and `fbp2020.de` as alias. When I type `fbp2020.de` in the browser, it leads me to `www.fbp2020.de`, and the `www.` part doesn't show up. If I fix the url to be `https://fbp2020.de`, then it works fine.

In the config of pretalx, the url is `fbp2020.de`

**Comment by rixx** [comment]
Hmm, URLs would need to be exactly correct between the pretalx configuration and the callback URL configured in ORCID. As long as this bug only occurs when the URL config is inconsistent, I'm not sure this is actually a pretalx bug.

I'd recommend being strict about using one domain for pretalx, and redirecting from or to the www. subdomain (and making sure that the ORCID redirect URL matches the domain).

**Comment by xhub** [comment]
I agree that the root cause is likely not a pretalx bug, and with your recommendation.

Pretalx is happy to serve the pages with `www.fbp2020.de`. It is just when I try to use the plugin that it fails. In that sense it is a bit inconsistent, and I would rather have it being consistent, and refuse to serve pages with  `www.fbp2020.de`. It would save some debugging time :)

If it's not easy to make it possible to support that the current browser url is used, it is possible to have the plugin check for consistency between the http header and the configuration?

Note that I tried to have the return url changed, this didn't seem to fix it.

**Comment by rixx** [comment]
Hm. pretalx is supposed to redirect to the configured URL if an event has a special URL configured, and otherwise complain about an unconfigured domain. There is a specific error for this, so I'm wondering why this was not triggered, and at which point there is a redirect to the www. subdomain. Is the www subdomain maybe configured as event specific domain?
